DK starting zone and dragonflight route update
Rycia/azeroth-pilot-reloaded pull request #122
Opened 2023-02-06 21:24 UTC by Neogeekmo

CF localization✅ 

close #121

2023-02-07 01:20 UTC, Rycia approved these changes

2023-02-07 01:51 UTC, Pahonix commented on APR-Core/Core.lua
> +			tinsert(APR_Custom[APR.Name.."-"..APR.Realm],"08-30 Dark Knight Start")
Should be "Death Knight"

2023-02-07 01:52 UTC, Pahonix commented on APR-Core/zones/Alliance.lua
> +		 ["08-30 Dark Knight Start"] = 23,
Should be "Death Knight"

2023-02-07 01:52 UTC, Pahonix commented on APR-Core/zones/Alliance.lua
> +			APR.QuestStepListListing["MISC 1"]["A23-ScarletEnclave"] = "08-30 Dark Knight Start"
Should be "Death Knight"

2023-02-07 01:52 UTC, Pahonix commented on APR-Core/zones/Horde.lua
> +		 ["08-30 Dark Knight Start"] = 23,
Should be "Death Knight"

2023-02-07 01:52 UTC, Pahonix commented on APR-Core/zones/Horde.lua
> +			APR.QuestStepListListing["MISC 1"]["H23-ScarletEnclave"] = "08-30 Dark Knight Start"
Should be "Death Knight"

2023-02-07 01:58 UTC, Pahonix commented on APR-WrathOfTheLichKing/WrathOfTheLichKing_Alliance.lua
> +                  12743,
Insert "12742," -- the DB array has to include the questID in the step. I missed that initially and fixed it already in the spreadsheet.

2023-02-07 01:58 UTC, Pahonix commented on APR-WrathOfTheLichKing/WrathOfTheLichKing_Alliance.lua
> +                  12743,
Insert "12742," -- the DB array has to include the questID in the step. I missed that initially and fixed it already in the spreadsheet.

2023-02-07 01:58 UTC, Pahonix commented on APR-WrathOfTheLichKing/WrathOfTheLichKing_Alliance.lua
> +                  12743,
Insert "12742," -- the DB array has to include the questID in the step. I missed that initially and fixed it already in the spreadsheet.

2023-02-07 02:00 UTC, Pahonix commented on APR-WrathOfTheLichKing/WrathOfTheLichKing_Horde.lua
> +                  12747,
Insert "12739," -- the DB array has to include the questID in the step. I missed that initially and fixed it already in the spreadsheet.

2023-02-07 02:00 UTC, Pahonix commented on APR-WrathOfTheLichKing/WrathOfTheLichKing_Horde.lua
> +                  12747,
Insert "12739," -- the DB array has to include the questID in the step. I missed that initially and fixed it already in the spreadsheet.

2023-02-07 02:00 UTC, Pahonix commented on APR-WrathOfTheLichKing/WrathOfTheLichKing_Horde.lua
> +                  12747,
Insert "12739," -- the DB array has to include the questID in the step. I missed that initially and fixed it already in the spreadsheet.

2023-02-07 02:02 UTC, Pahonix requested changes
Added a few comments for changes.

2023-02-08 14:26 UTC, NightofStarrs requested changes
@Neogeekmo, can you fix the 'Dark Knight' to 'Death Knight', I know it is how it is written in French. However, for consistency speaking it should be all the same/English verbiage. 

Additionally, Paho made some comments about correcting a few spots that the google sheet didn't have, or the export didn't grab.

2023-02-08 22:27 UTC, NightofStarrs approved these changes

2023-02-08 22:28 UTC, NightofStarrs commented
I approved it, but I still had Merging blocked. Prefer to wait for Paho to confirm everything is good first.

2023-02-09 00:58 UTC, Pahonix approved these changes

2023-02-09 00:58 UTC, merged